name: Debug OIDC Token

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  debug-oidc:
    name: Debug OIDC Token
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Get OIDC token
      run: |
        echo "🔍 Getting OIDC token..."
        
        # Get the OIDC token
        TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r .value)
        
        echo "Token length: ${#TOKEN}"
        echo "Token (first 100 chars): ${TOKEN:0:100}..."
        
        # Decode the JWT token (header and payload)
        echo "🔍 Decoding JWT token..."
        
        # Split the token into parts
        IFS='.' read -r header payload signature <<< "$TOKEN"
        
        # Decode header
        echo "Header:"
        echo "$header" | base64 -d | jq .
        
        # Decode payload
        echo "Payload:"
        echo "$payload" | base64 -d | jq .
        
    - name: Test STS call with debug
      run: |
        echo "🔍 Testing STS call with detailed error..."
        
        # Get the OIDC token
        TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r .value)
        
        # Test STS call with verbose output
        aws sts assume-role-with-web-identity \
          --role-arn arn:aws:iam::762233763891:role/GitHubActions-SoundBite-Dev \
          --web-identity-token $TOKEN \
          --role-session-name github-actions-debug \
          --region us-east-1 \
          --output json || echo "STS call failed"
