name: 'Deploy via SSM and Docker Compose'
description: 'Deploys to EC2 via SSM running docker-compose steps'

inputs:
  instance-id:
    description: 'EC2 instance ID to target'
    required: true
  environment:
    description: 'staging or production'
    required: true
  ecr-registry:
    description: 'ECR registry url'
    required: true
  ecr-repository:
    description: 'ECR repository name'
    required: true
  image-tag:
    description: 'Image tag to deploy'
    required: true
  aws-region:
    description: 'AWS region'
    required: false
    default: 'us-east-1'

runs:
  using: 'composite'
  steps:
    - id: deploy
      shell: bash
      run: |
        set -euo pipefail
        ENVIRONMENT='${{ inputs.environment }}'
        IMAGE_TAG='${{ inputs.image-tag }}'

        cmds=()
        cmds+=("echo \"ðŸš€ Starting Docker Compose deployment for $ENVIRONMENT...\"")
        cmds+=("echo \"ðŸ”§ Ensuring docker-compose is installed...\"")
        cmds+=("which docker-compose || (curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64 -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose)")
        cmds+=("docker-compose --version")
        cmds+=("echo \"ðŸ“¦ Cloning/updating repository...\"")
        cmds+=("cd /home/ec2-user")
        cmds+=("echo 'ðŸ“¥ Ensuring git is installed...'")
        cmds+=("which git || (sudo yum -y install git || sudo dnf -y install git)")
        cmds+=("if [ -d SoundBite ]; then cd SoundBite; else git clone https://github.com/SinaVosooghi/SoundBite.git && cd SoundBite; fi")
        cmds+=("if [[ \"$ENVIRONMENT\" == \"staging\" ]]; then git fetch --all && git checkout staging && git pull; else git fetch --all && git checkout master && git pull; fi")
        cmds+=("cd /home/ec2-user/SoundBite/docker || cd /home/ec2-user/SoundBite")
        cmds+=("aws ecr get-login-password --region ${{ inputs.aws-region }} | docker login --username AWS --password-stdin ${{ inputs.ecr-registry }}")
        cmds+=("echo \"âœï¸  Writing .env for compose with resolved tags...\"")
        cmds+=("echo ECR_REGISTRY=${{ inputs.ecr-registry }} > .env")
        cmds+=("echo ECR_REPOSITORY=${{ inputs.ecr-repository }} >> .env")
        cmds+=("if [[ \"$ENVIRONMENT\" == \"staging\" ]]; then echo STAGING_TAG=$IMAGE_TAG >> .env; else echo PRODUCTION_TAG=$IMAGE_TAG >> .env; fi")
        cmds+=("echo \"ðŸ“¦ Pulling latest image for target service...\"")
        cmds+=("if [[ \"$ENVIRONMENT\" == \"staging\" ]]; then docker-compose -f docker-compose.ec2.yml pull soundbite-staging; else docker-compose -f docker-compose.ec2.yml pull soundbite-production; fi")
        cmds+=("echo \"ðŸ›‘ Stopping existing services...\"")
        cmds+=("if [[ \"$ENVIRONMENT\" == \"staging\" ]]; then docker-compose -f docker-compose.ec2.yml stop soundbite-staging || true; else docker-compose -f docker-compose.ec2.yml stop soundbite-production || true; fi")
        cmds+=("echo \"ðŸ§¹ Cleaning up Docker to free space...\"")
        cmds+=("docker system prune -f || true")
        cmds+=("echo \"ðŸš€ Starting target service with Docker Compose...\"")
        cmds+=("if [[ \"$ENVIRONMENT\" == \"staging\" ]]; then docker-compose -f docker-compose.ec2.yml up -d soundbite-staging nginx; else docker-compose -f docker-compose.ec2.yml up -d soundbite-production nginx; fi")
        cmds+=("echo \"â³ Waiting for health checks...\"")
        cmds+=("sleep 30")
        cmds+=("echo \"ðŸ” Checking service status...\"")
        cmds+=("docker-compose -f docker-compose.ec2.yml ps | cat")
        cmds+=("echo \"ðŸŽ‰ Docker Compose deployment completed!\"")

        params_json=$(printf '%s
' "${cmds[@]}" | jq -R . | jq -s '{commands: .}')

        COMMAND_ID=$(aws ssm send-command \
          --instance-ids "${{ inputs.instance-id }}" \
          --document-name "AWS-RunShellScript" \
          --parameters "$params_json" \
          --region "${{ inputs.aws-region }}" \
          --query 'Command.CommandId' \
          --output text)

        echo "command-id=$COMMAND_ID" >> $GITHUB_OUTPUT

