name: Debug OIDC Connection

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  debug-oidc:
    name: Debug OIDC Connection
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Debug OIDC Token
      run: |
        echo "🔍 Debugging OIDC Token..."
        echo "ACTIONS_ID_TOKEN_REQUEST_URL: $ACTIONS_ID_TOKEN_REQUEST_URL"
        echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN: $ACTIONS_ID_TOKEN_REQUEST_TOKEN"
        
        # Get the OIDC token
        TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r .value)
        echo "OIDC Token (first 50 chars): ${TOKEN:0:50}..."
        
        # Decode the token to see its contents
        echo "🔍 Decoding OIDC Token..."
        echo $TOKEN | cut -d. -f2 | base64 -d | jq .
        
    - name: Test AWS STS directly
      run: |
        echo "🔍 Testing AWS STS directly..."
        TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r .value)
        
        # Try to assume the role directly
        aws sts assume-role-with-web-identity \
          --role-arn arn:aws:iam::762233763891:role/GitHubActions-SoundBite-Dev \
          --web-identity-token $TOKEN \
          --role-session-name github-actions-test \
          --region us-east-1
