name: Staging/Production CD Minimal

on:
  push:
    branches: [ staging, master ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 762233763891.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: soundbite-development-api
  DOCKER_PROD_FILE: ./Dockerfile

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::762233763891:role/GitHubActions-SoundBite-Prod
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Test step
        run: echo "CD workflow is working"
