name: Test OIDC Connection

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - production

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  test-oidc:
    name: Test OIDC Connection
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    timeout-minutes: 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID_DEV }}:role/GitHubActions-SoundBite-Dev
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Test AWS connection
      run: |
        echo "🔍 Testing AWS OIDC connection..."
        aws sts get-caller-identity
        echo "✅ OIDC connection successful!"
        
    - name: Test AWS services access
      run: |
        echo "🔍 Testing AWS services access..."
        aws s3 ls || echo "S3 access test completed"
        aws dynamodb list-tables || echo "DynamoDB access test completed"
        aws sqs list-queues || echo "SQS access test completed"
        echo "✅ AWS services access test completed!"
