name: Test OIDC with Environment Context

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-oidc-env:
    name: Test OIDC with Environment Context
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Get OIDC token with environment context
      run: |
        echo "🔍 Getting OIDC token with environment context..."
        
        # Get the OIDC token
        TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r .value)
        
        echo "Token length: ${#TOKEN}"
        
        # Decode the JWT token payload
        IFS='.' read -r header payload signature <<< "$TOKEN"
        
        echo "Payload:"
        echo "$payload" | base64 -d | jq .
        
    - name: Test STS call with environment context
      run: |
        echo "🔍 Testing STS call with environment context..."
        
        # Get the OIDC token
        TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r .value)
        
        # Test STS call
        aws sts assume-role-with-web-identity \
          --role-arn arn:aws:iam::762233763891:role/GitHubActions-SoundBite-Dev \
          --web-identity-token $TOKEN \
          --role-session-name github-actions-env-test \
          --region us-east-1 \
          --output json || echo "STS call failed"
